/**************************************************************************
 * Copyright (C) 2020 ASH WARE, Inc.
 *************************************************************************/
/**************************************************************************
* FILE NAME: etpu_init.c
* 
* DESCRIPTION: API implementation for initializing the eTPU module
*
*
*========================================================================
* REV      AUTHOR      DATE        DESCRIPTION OF CHANGE                 
* ---   -----------  ----------    ---------------------                 
* 1.0     J Diener   01/Jun/20     Initial version.     
*
**************************************************************************/

#include "etpu_util_ext.h"


// ALL OF THE BELOW INCLUDES SHOULD BE CAREFULLY CONTROLLED BY THE BUILD
// TO COME FROM THE CORRECT LOCATION, SO THAT THE SYSTEM IS INITIALIZED AS
// EXPECTED FOR THE GIVEN APP / SYSTEM BUILD

#include "etpu_ab_set_defines.h"  /* API macros, auto-generated by ETEC */
#include "etpu_ab_set_scm.c"  /* SCM code image, auto-generated by ETEC */
#include "etpu_ab_set_idata.c"  /* initialized data (global, engine (eTPU2), channel frame), auto-generated by ETEC */

#if defined(MPC5777C)
#include "etpu_c_set_defines.h"  /* API macros, auto-generated by ETEC */
#include "etpu_c_set_scm.c"  /* SCM code image, auto-generated by ETEC */
#include "etpu_c_set_idata.c"  /* initialized data (global, engine (eTPU2), channel frame), auto-generated by ETEC */
#endif

#include "etpu_config.h"  /* config specific for target & app (eTPU host interface register init structure */


/*------------------------------------------------------------------------------*/
uint32_t etpu_init()
{
	uint32_t return_val;

	/* initialize eTPU hardware */
	return_val = fs_etpu_init_ext(EM_AB,
	   &my_etpu_config, 
	   (uint32_t *) _SCM_code_mem_array, sizeof (_SCM_code_mem_array),
	   (uint32_t *) _global_mem_init, sizeof (_global_mem_init) );
#if defined(MPC5777C)
	return_val |= fs_etpu2_init_ext(EM_AB,
	   &my_etpu_config, 0);
#endif

	/* set the channel frame base address properly - channel frames will be allocated */
	/* starting at this address */
	/* this overrides the default init in fs_etpu_init(); in most cases the value will */
	/* the same, except when engine RAM is used */
	fs_etpu_free_param = (uint32_t*)(fs_etpu_data_ram_start + _CHANNEL_FRAME_2ETPU_BASE_ADDR);

#if defined(MPC5777C)
	return_val = fs_etpu_init_ext(EM_C,
	   &my_etpu_c_config, 
	   (uint32_t *) C_SCM_code_mem_array, sizeof (C_SCM_code_mem_array),
	   (uint32_t *) C_global_mem_init, sizeof (C_global_mem_init) );
	return_val |= fs_etpu2_init_ext(EM_C,
	   &my_etpu_c_config, 0);

	/* set the channel frame base address properly - channel frames will be allocated */
	/* starting at this address */
	/* this overrides the default init in fs_etpu_init(); in most cases the value will */
	/* the same, except when engine RAM is used */
	fs_etpu_c_free_param = (uint32_t*)(fs_etpu_c_data_ram_start + C_CHANNEL_FRAME_1ETPU_BASE_ADDR);
#endif

	return return_val;
}
